FROM balenalib/aarch64-alpine-golang:3.18-build as builder

WORKDIR /usr/src/app
COPY . ./

RUN go install && \
    go build -o bin/notecard

FROM balenalib/aarch64-alpine:3.18-run as runner

COPY --from=builder /usr/src/app/bin/notecard ./notecard

CMD ["./notecard"]